### ISSUE TITLE
LoFreq v.2.1.2 pre-compiled for OS X does not works in some OS versions

### ISSUE THREAD

**Issue by magicDGS** [CSB5/lofreq#27]
Pre-compiled version does not work in OS X 10.8.5 (12F2560) but it works in OS X 10.9.5 (13F1507), because of the __libSystem.B.dylib__:
```
dyld: Symbol not found: ___exp10
  Referenced from: lofreq
  Expected in: /usr/lib/libSystem.B.dylib
```
I understand that it could not be compiled for every OS, but I would appreciate if it could be specified somewhere for which version could be used, because it does not complain until it needs this function.

It is not a major issue, because when I compiled the source in my computer is working perfectly, but for a final user it could be a problem.

**Comment by andreas-wilm** [comment]
For this I rely entirely on user input. I only have access to 10.9 machines. Will therefore keep this open for users reference
